import { ordersAPI } from "@/api/orders.api";
import { CreateOrderData, Order, OrderStatus, UpdateOrderData } from "@/types/orders";
import { useCallback, useEffect, useRef, useState } from "react";
import { toast } from "./use-toast";

export const useOrderManagement = () => {
  const [currentOrder, setCurrentOrder] = useState<Order | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const autoSaveTimeoutRef = useRef<NodeJS.Timeout | null>(null);
  const lastSavedRef = useRef<string>("");

  // Auto-save functionality
  const scheduleAutoSave = useCallback((order: Order) => {
    if (autoSaveTimeoutRef.current) {
      clearTimeout(autoSaveTimeoutRef.current);
    }

    const orderString = JSON.stringify({
      items: order.items,
      customerName: order.customerName,
      customerPhone: order.customerPhone,
      notes: order.notes
    });

    // Only save if something actually changed
    if (orderString === lastSavedRef.current) {
      return;
    }

    autoSaveTimeoutRef.current = setTimeout(async () => {
      try {
        await ordersAPI.autoSaveOrder(order.id, {
          items: order.items.map(item => ({
            materialId: item.materialId,
            menuItemId: item.menuItemId,
            assignmentId: item.assignmentId,
            name: item.name,
            quantity: item.quantity,
            unitPrice: item.unitPrice,
            totalPrice: item.totalPrice,
            type: item.type,
            notes: item.notes
          })),
          customerName: order.customerName,
          customerPhone: order.customerPhone,
          notes: order.notes
        });
        lastSavedRef.current = orderString;
        console.log("Order auto-saved successfully");
      } catch (error) {
        console.error("Auto-save failed:", error);
      }
    }, 2000); // Auto-save after 2 seconds of inactivity
  }, []);

  // Create a new order
  const createOrder = useCallback(async (data: CreateOrderData): Promise<Order> => {
    setIsLoading(true);
    setError(null);

    try {
      // Backend will generate sequential order number automatically
      const orderData = {
        ...data
        // orderNumber will be generated by backend if not provided
      };

      console.log("Creating order - backend will generate order number");
      console.log("🚀 Making API call to ordersAPI.createOrder with:", orderData);
      
      const response = await ordersAPI.createOrder(orderData);
      console.log("📦 API response received:", response);
      
      const newOrder = response.data;
      console.log("🎆 New order created:", newOrder);
      
      setCurrentOrder(newOrder);
      console.log("💾 Order saved to state");
      
      return newOrder;
    } catch (error: unknown) {
      console.error("❌ Order creation failed with error:", error);
      console.error("🔍 Error details:", {
        message: (error as any)?.message,
        response: (error as any)?.response,
        status: (error as any)?.response?.status,
        data: (error as any)?.response?.data
      });
      
      const errorMessage = (error as any)?.response?.data?.message || "Failed to create order";
      console.error("🚨 Setting error message:", errorMessage);
      
      setError(errorMessage);
      toast({
        title: "Error",
        description: errorMessage,
        variant: "destructive"
      });
      throw error;
    } finally {
      setIsLoading(false);
    }
  }, []);

  // Load an existing order
  const loadOrder = useCallback(async (orderId: string): Promise<Order> => {
    setIsLoading(true);
    setError(null);

    try {
      const response = await ordersAPI.getOrder(orderId);
      // Handle nested response structure - API sometimes returns nested data
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const responseData = response.data as { data?: any } | any;
      const order = responseData.data || responseData;
      setCurrentOrder(order);
      return order;
    } catch (error: unknown) {
      const errorMessage = (error as any)?.response?.data?.message || "Failed to load order";
      setError(errorMessage);
      toast({
        title: "Error",
        description: errorMessage,
        variant: "destructive"
      });
      throw error;
    } finally {
      setIsLoading(false);
    }
  }, []);

  // Update current order
  const updateOrder = useCallback(
    async (data: UpdateOrderData): Promise<Order> => {
      if (!currentOrder) {
        throw new Error("No current order to update");
      }

      setIsLoading(true);
      setError(null);

      try {
        // Handle nested currentOrder structure
        console.log("🔍 updateOrder - currentOrder:", currentOrder);
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const orderId = currentOrder.id || (currentOrder as any)?.data?.id;
        console.log("🔍 updateOrder - extracted orderId:", orderId);
        if (!orderId) {
          console.error("🔍 updateOrder - No valid order ID found!");
          throw new Error("No valid order ID found in currentOrder");
        }

        console.log("🔍 updateOrder - calling API with orderId:", orderId);
        const response = await ordersAPI.updateOrder(orderId, data);
        // Handle nested response structure
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const responseData = response.data as { data?: any } | any;
        const updatedOrder = responseData.data || responseData;
        setCurrentOrder(updatedOrder);

        // Schedule auto-save for draft orders
        if (updatedOrder.status === "draft") {
          scheduleAutoSave(updatedOrder);
        }

        return updatedOrder;
      } catch (error: unknown) {
        const errorMessage = (error as any)?.response?.data?.message || "Failed to update order";
        setError(errorMessage);
        toast({
          title: "Error",
          description: errorMessage,
          variant: "destructive"
        });
        throw error;
      } finally {
        setIsLoading(false);
      }
    },
    [currentOrder, scheduleAutoSave]
  );

  // Update order status
  const updateOrderStatus = useCallback(
    async (status: OrderStatus): Promise<Order> => {
      if (!currentOrder) {
        throw new Error("No current order to update");
      }

      setIsLoading(true);
      setError(null);

      try {
        const response = await ordersAPI.updateOrderStatus(currentOrder.id, status);
        const updatedOrder = response.data;
        setCurrentOrder(updatedOrder);

        toast({
          title: "Order Updated",
          description: `Order status changed to ${status}`,
          variant: "default"
        });

        return updatedOrder;
      } catch (error: unknown) {
        const errorMessage = (error as any)?.response?.data?.message || "Failed to update order status";
        setError(errorMessage);
        toast({
          title: "Error",
          description: errorMessage,
          variant: "destructive"
        });
        throw error;
      } finally {
        setIsLoading(false);
      }
    },
    [currentOrder]
  );

  // Complete order (convert to sale)
  const completeOrder = useCallback(
    async (paymentData: { paymentMethod: string; paymentAmount: number; change?: number }) => {
      if (!currentOrder) {
        throw new Error("No current order to complete");
      }

      setIsLoading(true);
      setError(null);

      try {
        const response = await ordersAPI.completeOrder(currentOrder.id, paymentData);
        const { order, saleId } = response.data;

        // Clear current order after completion
        setCurrentOrder(null);

        toast({
          title: "Order Completed",
          description: `Order completed successfully. Sale ID: ${saleId}`,
          variant: "default"
        });

        return { order, saleId };
      } catch (error: unknown) {
        const errorMessage = (error as any)?.response?.data?.message || "Failed to complete order";
        setError(errorMessage);
        toast({
          title: "Error",
          description: errorMessage,
          variant: "destructive"
        });
        throw error;
      } finally {
        setIsLoading(false);
      }
    },
    [currentOrder]
  );

  // Void order (enhanced cancellation with stock restoration)
  const voidOrder = useCallback(
    async (reason?: string, restoreStock: boolean = true) => {
      if (!currentOrder) {
        throw new Error("No current order to void");
      }

      setIsLoading(true);
      setError(null);

      try {
        // Handle nested currentOrder structure
        const orderId = currentOrder.id || (currentOrder as any)?.data?.id;
        if (!orderId) {
          throw new Error("No valid order ID found in currentOrder");
        }

        console.log("🚫 Voiding order:", orderId, "with reason:", reason);

        const response = await ordersAPI.voidOrder(orderId, {
          reason: reason || "Order voided by user",
          restoreStock
        });

        // Handle nested response structure
        const responseData = response.data as { order?: any; stockRestorations?: any[] } | any;
        const voidedOrder = responseData.order || responseData;
        const stockRestorations = responseData.stockRestorations;

        // Clear current order after voiding
        setCurrentOrder(null);

        // Show success message with stock restoration info
        let successMessage = "Order voided successfully";
        if (stockRestorations && stockRestorations.length > 0) {
          successMessage += `. Stock restored for ${stockRestorations.length} item(s).`;
        }

        toast({
          title: "Order Voided",
          description: successMessage,
          variant: "default"
        });

        return { order: voidedOrder, stockRestorations };
      } catch (error: unknown) {
        const errorMessage = (error as any)?.response?.data?.message || "Failed to void order";
        setError(errorMessage);
        toast({
          title: "Error",
          description: errorMessage,
          variant: "destructive"
        });
        throw error;
      } finally {
        setIsLoading(false);
      }
    },
    [currentOrder]
  );

  // Clear current order
  const clearOrder = useCallback(() => {
    if (autoSaveTimeoutRef.current) {
      clearTimeout(autoSaveTimeoutRef.current);
    }
    setCurrentOrder(null);
    setError(null);
    lastSavedRef.current = "";
  }, []);

  // Cleanup on unmount
  useEffect(() => {
    return () => {
      if (autoSaveTimeoutRef.current) {
        clearTimeout(autoSaveTimeoutRef.current);
      }
    };
  }, []);

  return {
    currentOrder,
    isLoading,
    error,
    createOrder,
    loadOrder,
    updateOrder,
    updateOrderStatus,
    completeOrder,
    voidOrder,
    clearOrder
  };
};
