import { Employee } from "./employee";
import { MenuItem, NegativeStockWarning, POSCartItem, ReceiptData, SaleResponse, SectionAssignment, StockEntryWithMaterial, Table } from "./inventory";
import { OrderType } from "./orders";
import { OrderSummary as OrderSummaryType } from "@/types/orders";

export interface UsePOSDataProps {
  sectionAssignments: SectionAssignment[];
  showError: (message: string) => void;
}

export interface POSLayoutProps {
  leftPanelWidth: number;
  setLeftPanelWidth: (width: number) => void;
  rightPanelPixelWidth: number;
  setRightPanelPixelWidth: (width: number) => void;
  isResizing: boolean;
  setIsResizing: (resizing: boolean) => void;
  containerRef: React.RefObject<HTMLDivElement>;
  activeView: "cart" | "products";
  setActiveView: (view: "cart" | "products") => void;
  cart: POSCartItem[];
  orderType: OrderType;
  selectedTable: Table | undefined;
  selectedEmployee: Employee | undefined;
  subtotal: number;
  total: number;
  hasUnsavedChanges: boolean;
  showSuccessCheckmark: boolean;
  currentOrder: any;
  appliedDiscount: { type: "percentage" | "fixed"; value: number; amount: number; reason?: string } | null;
  categories: string[];
  activeCategory: string;
  setActiveCategory: (category: string) => void;
  filteredPosItems: any[];
  isProductsLoading: boolean;
  incompleteTableOrdersCount: number;
  incompleteOrdersCount: number;
  incompleteDeliveryTakeawayCount: number;
  updateCartQuantity: (cartId: string, newQuantity: number) => void;
  onOrderTypeChange: (type: OrderType) => void;
  onTableSelect: () => void;
  onEmployeeSelect: (employee: Employee) => void;
  onItemNotesChange: (itemId: string, notes: string) => void;
  onShowItemNotes: (item: POSCartItem) => void;
  onRemoveDiscount: () => void;
  onPaymentClick: () => void;
  onSaveClick: () => void;
  onAddToCart: (item: any) => void;
  clearCart: () => void;
  onSaveOrder: () => void;
  onPrintReceipt: () => void;
  onVoidOrder: () => void;
  onShowOrders: () => void;
  onShowReports: () => void;
  onCancelOrder: () => void;
  onDiscount: () => void;
  onShowPrinterSettings: () => void;
  hasSavedPrinter: boolean;
  savedPrinterName?: string;
  isOrderLoading: boolean;
  canPrintReceipt: boolean;
  canVoidOrder: boolean;
  previewOrderNumber?: string;
}

export interface UsePOSCartProps {
  cart: POSCartItem[];
  setCart: (cart: POSCartItem[] | ((prevCart: POSCartItem[]) => POSCartItem[])) => void;
  menuItems: MenuItem[];
  stockEntries: StockEntryWithMaterial[];
  tables: any[];
  optimisticAssignments: any[];
  showSuccess: (message: string) => void;
  recalculateEmployeeDiscount: (cart: POSCartItem[]) => void;
  setHasUnsavedChanges: (hasChanges: boolean) => void;
}

export interface POSDialogsProps {
  showPaymentDialog: boolean;
  setShowPaymentDialog: (show: boolean) => void;
  total: number;
  paymentAmount: string;
  setPaymentAmount: (amount: string) => void;
  onPayment: (paymentData: { amount: number; method: string }) => Promise<void>;
  isLoading: boolean;
  showReceiptDialog: boolean;
  setShowReceiptDialog: (show: boolean) => void;
  lastSaleData: ReceiptData | null;
  shouldAutoPrint: boolean;
  setShouldAutoPrint: (should: boolean) => void;
  showDiscountDialog: boolean;
  setShowDiscountDialog: (show: boolean) => void;
  discountAmount: number;
  onDiscountAmountChange: (amount: number) => void;
  subtotal: number;
  onApplyDiscount: (discountData: { type: "percentage" | "fixed"; value: number; reason?: string }) => void;
  showNotesDialog: boolean;
  setShowNotesDialog: (show: boolean) => void;
  orderNotes: string;
  setOrderNotes: (notes: string) => void;
  showItemNotesDialog: boolean;
  setShowItemNotesDialog: (show: boolean) => void;
  selectedItemForNotes: POSCartItem | null;
  setSelectedItemForNotes: (item: POSCartItem | null) => void;
  onItemNotesChange: (itemId: string, notes: string) => void;
  showVoidDialog: boolean;
  setShowVoidDialog: (show: boolean) => void;
  currentOrder: any;
  orderLoading: boolean;
  onConfirmVoid: (reason: string, restoreStock: boolean) => void;
  showOrdersDialog: boolean;
  setShowOrdersDialog: (show: boolean) => void;
  onOrderSelect: (order: OrderSummaryType) => void;
  onOrderStatusChange: () => void;
  showTablesLayout: boolean;
  setShowTablesLayout: (show: boolean) => void;
  tables: Table[];
  selectedTable: Table | undefined;
  onTableSelect: (table: Table) => void;
  onCloseTablesLayout: () => void;
  tableOrders: { [tableId: string]: number };
  showReportsDialog: boolean;
  setShowReportsDialog: (show: boolean) => void;
  showPrinterSelector: boolean;
  setShowPrinterSelector: (show: boolean) => void;
  printerSelectionContext: "payment" | "manual_print" | null;
  selectedPrinter: any;
  onPrinterSelect: (printer: any) => void;
  onClosePrinterSelector: () => void;
  hasSavedPrinter: () => boolean;
  getSavedPrinter: () => any;
  clearPrinterSelection: () => void;
  showUnsavedDialog: boolean;
  setShowUnsavedDialog: (show: boolean) => void;
  onSaveOrder: () => void;
  showNegativeStockDialog: boolean;
  setShowNegativeStockDialog: (show: boolean) => void;
  negativeStockWarnings: NegativeStockWarning[];
  successMessage: string | null;
  error: string | null;
  showSuccess: (message: string) => void;
  showError: (message: string) => void;
}

export interface UsePOSHandlersProps {
  cart: POSCartItem[];
  setCart: (cart: POSCartItem[] | ((prevCart: POSCartItem[]) => POSCartItem[])) => void;
  orderType: OrderType;
  setOrderType: (type: OrderType) => void;
  selectedTable: Table | undefined;
  setSelectedTable: (table: Table | undefined) => void;
  selectedEmployee: Employee | undefined;
  setSelectedEmployee: (employee: Employee | undefined) => void;
  appliedDiscount: { type: "percentage" | "fixed"; value: number; amount: number; reason?: string } | null;
  setAppliedDiscount: (discount: any) => void;
  discountAmount: number;
  setDiscountAmount: (amount: number) => void;
  orderNotes: string;
  setOrderNotes: (notes: string) => void;
  paymentAmount: string;
  setPaymentAmount: (amount: string) => void;
  lastSaleData: ReceiptData | null;
  setLastSaleData: (data: ReceiptData | null) => void;
  showError: (message: string) => void;
  showSuccess: (message: string) => void;
  clearCartWithAnimation: () => void;
  clearCart: () => void;
  setHasUnsavedChanges: (hasChanges: boolean) => void;
  setShowTablesLayout: (show: boolean) => void;
  setShowReceiptDialog: (show: boolean) => void;
  setShouldAutoPrint: (should: boolean) => void;
  setShowPaymentDialog: (show: boolean) => void;
  setShowPrinterSelector: (show: boolean) => void;
  setPrinterSelectionContext: (context: "payment" | "manual_print" | null) => void;
  printerSelectionContext: "payment" | "manual_print" | null;
  tables: Table[];
  setTables: (tables: Table[]) => void;
  menuItems: MenuItem[];
  stockEntries: StockEntryWithMaterial[];
  subtotal: number;
  total: number;
  tax: number;
  refreshOrderData: () => Promise<void>;
  refreshAllCounts: () => Promise<void>;
  fetchTablesData: () => Promise<void>;
  onSaleComplete?: (response: SaleResponse) => void;
  onOrderProcessed?: () => void;
}
