import api from "@/lib/http";
import { CreateFloorPlanRequest, FloorPlan, FloorPlanResponse, FloorPlansResponse, FloorPlanTablesResponse } from "../types/floor-plan";

export const floorPlanAPI = {
  getFloorPlans: async (params?: { includeAreas?: boolean; includeInactive?: boolean }): Promise<FloorPlansResponse> => {
    const searchParams = new URLSearchParams();
    if (params?.includeAreas) searchParams.append("includeAreas", "true");
    if (params?.includeInactive) searchParams.append("includeInactive", "true");

    const response = await api.get<FloorPlansResponse>(`/floor-plans?${searchParams.toString()}`);
    return response.data;
  },

  // Get specific floor plan
  getFloorPlan: async (floorPlanId: string): Promise<FloorPlanResponse> => {
    const response = await api.get<FloorPlanResponse>(`/floor-plans/${floorPlanId}`);
    return response.data;
  },

  // Create new floor plan
  createFloorPlan: async (data: CreateFloorPlanRequest): Promise<FloorPlanResponse> => {
    const response = await api.post<FloorPlanResponse, CreateFloorPlanRequest>("/floor-plans", data);
    return response.data;
  },

  // Update floor plan
  updateFloorPlan: async (floorPlanId: string, data: Partial<CreateFloorPlanRequest>): Promise<FloorPlanResponse> => {
    const response = await api.put<FloorPlanResponse, Partial<CreateFloorPlanRequest>>(`/floor-plans/${floorPlanId}`, data);
    return response.data;
  },

  // Delete floor plan
  deleteFloorPlan: async (floorPlanId: string): Promise<{ message: string }> => {
    const response = await api.delete<{ message: string }>(`/floor-plans/${floorPlanId}`);
    return response.data;
  },

  // Set default floor plan
  setDefaultFloorPlan: async (floorPlanId: string): Promise<FloorPlanResponse> => {
    const response = await api.patch<FloorPlanResponse, Record<string, never>>(`/floor-plans/${floorPlanId}/default`, {});
    return response.data;
  },

  // Get tables from floor plan (for POS integration)
  getFloorPlanTables: async (
    floorPlanId: string = "default",
    params?: {
      section?: string;
      status?: string;
      includeOrders?: boolean;
    }
  ): Promise<FloorPlanTablesResponse> => {
    const searchParams = new URLSearchParams();
    if (params?.section) searchParams.append("section", params.section);
    if (params?.status) searchParams.append("status", params.status);
    if (params?.includeOrders) searchParams.append("includeOrders", "true");

    const response = await api.get<FloorPlanTablesResponse>(`/floor-plans/${floorPlanId}/tables?${searchParams.toString()}`);
    return response.data;
  },

  // Update furniture item status
  updateFurnitureStatus: async (furnitureItemId: number, status: string): Promise<{ message: string; data: { id: number; status: string } }> => {
    const response = await api.patch<{ message: string; data: { id: number; status: string } }, { status: string }>(`/floor-plans/furniture/${furnitureItemId}/status`, { status });
    return response.data;
  },

  // Save floor plan from designer
  saveFloorPlanFromDesigner: async (floorPlan: FloorPlan): Promise<FloorPlanResponse> => {
    const transformedData: CreateFloorPlanRequest = {
      name: floorPlan.name,
      description: `Floor plan created on ${new Date().toLocaleDateString()}`,
      areas: floorPlan.areas.map(area => ({
        name: area.name,
        bounds: area.bounds,
        color: area.color,
        section: area.name.toLowerCase().replace(/\s+/g, "_"),
        furniture: area.furniture.map(furniture => ({
          id: furniture.id,
          type: furniture.type,
          name: furniture.name,
          position: furniture.position,
          dimensions: furniture.dimensions,
          rotation: furniture.rotation,
          color: furniture.color,
          seatingCapacity: furniture.seatingCapacity,
          zIndex: furniture.zIndex,
          parentId: furniture.parentId
          // tableNumber: will be auto-generated by backend to avoid conflicts
        }))
      })),
      isDefault: false
    };

    // Determine if this is a new floor plan or an existing one
    // Frontend starts with default IDs like "1", "2" which are not backend IDs
    // Only attempt to update if the ID looks like a backend ID (numeric and was loaded from backend)
    const isDefaultLocalPlan = floorPlan.id === "1" || floorPlan.id === "new" || !floorPlan.id;

    if (isDefaultLocalPlan) {
      // This is a new floor plan (default template or new), always create
      console.log("Creating new floor plan (default template):", floorPlan.name);
      return await floorPlanAPI.createFloorPlan(transformedData);
    } else {
      // This might be an existing backend floor plan, check if it exists
      try {
        // Try to fetch the floor plan to see if it exists
        await floorPlanAPI.getFloorPlan(floorPlan.id);
        // If we get here, the floor plan exists, so update it
        console.log("Updating existing floor plan:", floorPlan.id, floorPlan.name);
        return await floorPlanAPI.updateFloorPlan(floorPlan.id, transformedData);
      } catch (error) {
        // Floor plan doesn't exist in backend, create a new one
        console.log("Floor plan not found in backend, creating new:", floorPlan.name);
        return await floorPlanAPI.createFloorPlan(transformedData);
      }
    }
  }
};
