/**
 * Returns a placeholder order number
 * The actual order number will be generated by the backend during order creation
 * Format: ORD-XXXX (e.g., ORD-0001, ORD-0002, etc.)
 */
export const fetchNextOrderNumber = async (): Promise<string> => {
  // Return placeholder - backend will generate the actual sequential number
  // when the order is created to avoid race conditions
  return "ORD-XXXX";
};
