import Material from "../models/materials.js";
import StockEntry from "../models/StockEntry.js";

/**
 * Seed stock entries based on RAW INGREDIENTS for proper inventory management
 */
export async function seedStockEntries() {
  console.log("📦 Seeding stock entries for raw ingredients...");

  // Get all materials
  const materials = await Material.findAll();
  const materialMap = {};
  materials.forEach(material => {
    materialMap[material.name] = material;
  });

  // Define stock entries with all required fields
  const stockEntries = [
    // =============================================================================
    // PROTEINS
    // =============================================================================
    { materialName: "Beef Patty", materialId: 1, purchasedQuantity: 50, purchasedUnit: "kg", purchasedIndividualQuantity: 50000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 50000, costPerPurchasedUnit: 12.0, costPerBaseUnit: 0.012, totalCost: 600, supplier: "Charles", isPOSItem: false },
    { materialName: "Chicken Breast", materialId: 2, purchasedQuantity: 40, purchasedUnit: "kg", purchasedIndividualQuantity: 40000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 40000, costPerPurchasedUnit: 8.5, costPerBaseUnit: 0.0085, totalCost: 340, supplier: "Charles", isPOSItem: false },
    { materialName: "Chicken Thigh", materialId: 3, purchasedQuantity: 30, purchasedUnit: "kg", purchasedIndividualQuantity: 30000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 30000, costPerPurchasedUnit: 7.0, costPerBaseUnit: 0.007, totalCost: 210, supplier: "Charles", isPOSItem: false },
    { materialName: "Crispy Chicken", materialId: 216, purchasedQuantity: 20, purchasedUnit: "pack", purchasedIndividualQuantity: 240, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "pack", purchasedConvertedQuantity: 20, costPerPurchasedUnit: 15.0, costPerBaseUnit: 1.25, totalCost: 300, supplier: "Charles", isPOSItem: false },
    { materialName: "Chicken Wings", materialId: 4, purchasedQuantity: 15, purchasedUnit: "pack", purchasedIndividualQuantity: 180, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "pack", purchasedConvertedQuantity: 15, costPerPurchasedUnit: 18.0, costPerBaseUnit: 1.5, totalCost: 270, supplier: "Charles", isPOSItem: false },
    { materialName: "Taouk", materialId: 5, purchasedQuantity: 25, purchasedUnit: "kg", purchasedIndividualQuantity: 25000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 25000, costPerPurchasedUnit: 9.0, costPerBaseUnit: 0.009, totalCost: 225, supplier: "Charles", isPOSItem: false },
    { materialName: "Beef Filet", materialId: 6, purchasedQuantity: 20, purchasedUnit: "kg", purchasedIndividualQuantity: 20000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 20000, costPerPurchasedUnit: 25.0, costPerBaseUnit: 0.025, totalCost: 500, supplier: "Charles", isPOSItem: false },
    { materialName: "Salmon", materialId: 7, purchasedQuantity: 15, purchasedUnit: "kg", purchasedIndividualQuantity: 15000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 15000, costPerPurchasedUnit: 22.0, costPerBaseUnit: 0.022, totalCost: 330, supplier: "Charles", isPOSItem: false },
    { materialName: "Shrimp", materialId: 8, purchasedQuantity: 12, purchasedUnit: "kg", purchasedIndividualQuantity: 12000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 12000, costPerPurchasedUnit: 28.0, costPerBaseUnit: 0.028, totalCost: 336, supplier: "Charles", isPOSItem: false },
    { materialName: "Tuna", materialId: 9, purchasedQuantity: 10, purchasedUnit: "kg", purchasedIndividualQuantity: 10000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 10000, costPerPurchasedUnit: 30.0, costPerBaseUnit: 0.03, totalCost: 300, supplier: "Charles", isPOSItem: false },
    { materialName: "Crab Sticks", materialId: 10, purchasedQuantity: 8, purchasedUnit: "kg", purchasedIndividualQuantity: 8000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 8000, costPerPurchasedUnit: 25.0, costPerBaseUnit: 0.025, totalCost: 200, supplier: "Charles", isPOSItem: false },
    { materialName: "Ham", materialId: 11, purchasedQuantity: 12, purchasedUnit: "kg", purchasedIndividualQuantity: 12000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 12000, costPerPurchasedUnit: 15.0, costPerBaseUnit: 0.015, totalCost: 180, supplier: "Charles", isPOSItem: false },
    { materialName: "Bacon", materialId: 12, purchasedQuantity: 8, purchasedUnit: "kg", purchasedIndividualQuantity: 8000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 8000, costPerPurchasedUnit: 18.0, costPerBaseUnit: 0.018, totalCost: 144, supplier: "Charles", isPOSItem: false },
    { materialName: "Pepperoni", materialId: 13, purchasedQuantity: 6, purchasedUnit: "kg", purchasedIndividualQuantity: 6000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 6000, costPerPurchasedUnit: 20.0, costPerBaseUnit: 0.02, totalCost: 120, supplier: "Charles", isPOSItem: false },
    { materialName: "Salami", materialId: 14, purchasedQuantity: 5, purchasedUnit: "kg", purchasedIndividualQuantity: 5000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 5000, costPerPurchasedUnit: 22.0, costPerBaseUnit: 0.022, totalCost: 110, supplier: "Charles", isPOSItem: false },

    // =============================================================================
    // DAIRY PRODUCTS
    // =============================================================================
    { materialName: "Mozzarella Cheese", materialId: 15, purchasedQuantity: 20, purchasedUnit: "kg", purchasedIndividualQuantity: 20000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 20000, costPerPurchasedUnit: 12.0, costPerBaseUnit: 0.012, totalCost: 240, supplier: "Charles", isPOSItem: false },
    { materialName: "Cheddar Cheese", materialId: 16, purchasedQuantity: 15, purchasedUnit: "kg", purchasedIndividualQuantity: 15000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 15000, costPerPurchasedUnit: 14.0, costPerBaseUnit: 0.014, totalCost: 210, supplier: "Charles", isPOSItem: false },
    { materialName: "Halloumi", materialId: 17, purchasedQuantity: 12, purchasedUnit: "kg", purchasedIndividualQuantity: 12000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 12000, costPerPurchasedUnit: 16.0, costPerBaseUnit: 0.016, totalCost: 192, supplier: "Charles", isPOSItem: false },
    { materialName: "Parmesan", materialId: 18, purchasedQuantity: 8, purchasedUnit: "kg", purchasedIndividualQuantity: 8000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 8000, costPerPurchasedUnit: 25.0, costPerBaseUnit: 0.025, totalCost: 200, supplier: "Charles", isPOSItem: false },
    { materialName: "Feta Cheese", materialId: 19, purchasedQuantity: 10, purchasedUnit: "kg", purchasedIndividualQuantity: 10000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 10000, costPerPurchasedUnit: 18.0, costPerBaseUnit: 0.018, totalCost: 180, supplier: "Charles", isPOSItem: false },
    { materialName: "Cream Cheese", materialId: 20, purchasedQuantity: 8, purchasedUnit: "kg", purchasedIndividualQuantity: 8000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 8000, costPerPurchasedUnit: 10.0, costPerBaseUnit: 0.01, totalCost: 80, supplier: "Charles", isPOSItem: false },
    { materialName: "Emental Cheese", materialId: 21, purchasedQuantity: 6, purchasedUnit: "kg", purchasedIndividualQuantity: 6000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 6000, costPerPurchasedUnit: 20.0, costPerBaseUnit: 0.02, totalCost: 120, supplier: "Charles", isPOSItem: false },
    { materialName: "Labneh", materialId: 22, purchasedQuantity: 15, purchasedUnit: "kg", purchasedIndividualQuantity: 15000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 15000, costPerPurchasedUnit: 8.0, costPerBaseUnit: 0.008, totalCost: 120, supplier: "Charles", isPOSItem: false },
    { materialName: "Eggs", materialId: 23, purchasedQuantity: 200, purchasedUnit: "piece", purchasedIndividualQuantity: 200, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "piece", purchasedConvertedQuantity: 200, costPerPurchasedUnit: 0.3, costPerBaseUnit: 0.3, totalCost: 60, supplier: "Charles", isPOSItem: false },

    // =============================================================================
    // VEGETABLES & PRODUCE
    // =============================================================================
    { materialName: "Iceberg Lettuce", materialId: 24, purchasedQuantity: 25, purchasedUnit: "kg", purchasedIndividualQuantity: 25000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 25000, costPerPurchasedUnit: 2.5, costPerBaseUnit: 0.0025, totalCost: 62.5, supplier: "Charles", isPOSItem: false },
    { materialName: "Rocca", materialId: 25, purchasedQuantity: 15, purchasedUnit: "kg", purchasedIndividualQuantity: 15000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 15000, costPerPurchasedUnit: 8.0, costPerBaseUnit: 0.008, totalCost: 120, supplier: "Charles", isPOSItem: false },
    { materialName: "Kale", materialId: 26, purchasedQuantity: 12, purchasedUnit: "kg", purchasedIndividualQuantity: 12000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 12000, costPerPurchasedUnit: 9.0, costPerBaseUnit: 0.009, totalCost: 108, supplier: "Charles", isPOSItem: false },
    { materialName: "Cherry Tomatoes", materialId: 27, purchasedQuantity: 20, purchasedUnit: "kg", purchasedIndividualQuantity: 20000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 20000, costPerPurchasedUnit: 3.5, costPerBaseUnit: 0.0035, totalCost: 70, supplier: "Charles", isPOSItem: false },
    { materialName: "Onion", materialId: 28, purchasedQuantity: 30, purchasedUnit: "kg", purchasedIndividualQuantity: 30000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 30000, costPerPurchasedUnit: 1.8, costPerBaseUnit: 0.0018, totalCost: 54, supplier: "Charles", isPOSItem: false },
    { materialName: "Bell Pepper", materialId: 29, purchasedQuantity: 18, purchasedUnit: "kg", purchasedIndividualQuantity: 18000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 18000, costPerPurchasedUnit: 4.0, costPerBaseUnit: 0.004, totalCost: 72, supplier: "Charles", isPOSItem: false },
    { materialName: "Mushroom", materialId: 30, purchasedQuantity: 15, purchasedUnit: "kg", purchasedIndividualQuantity: 15000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 15000, costPerPurchasedUnit: 8.0, costPerBaseUnit: 0.008, totalCost: 120, supplier: "Charles", isPOSItem: false },
    { materialName: "Avocado", materialId: 31, purchasedQuantity: 20, purchasedUnit: "kg", purchasedIndividualQuantity: 20000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 20000, costPerPurchasedUnit: 15.0, costPerBaseUnit: 0.015, totalCost: 300, supplier: "Charles", isPOSItem: false },
    { materialName: "Cucumber", materialId: 32, purchasedQuantity: 25, purchasedUnit: "kg", purchasedIndividualQuantity: 25000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 25000, costPerPurchasedUnit: 2.2, costPerBaseUnit: 0.0022, totalCost: 55, supplier: "Charles", isPOSItem: false },
    { materialName: "Carrot", materialId: 33, purchasedQuantity: 20, purchasedUnit: "kg", purchasedIndividualQuantity: 20000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 20000, costPerPurchasedUnit: 1.5, costPerBaseUnit: 0.0015, totalCost: 30, supplier: "Charles", isPOSItem: false },
    { materialName: "Red Cabbage", materialId: 34, purchasedQuantity: 15, purchasedUnit: "kg", purchasedIndividualQuantity: 15000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 15000, costPerPurchasedUnit: 2.8, costPerBaseUnit: 0.0028, totalCost: 42, supplier: "Charles", isPOSItem: false },
    { materialName: "Corn", materialId: 35, purchasedQuantity: 12, purchasedUnit: "kg", purchasedIndividualQuantity: 12000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 12000, costPerPurchasedUnit: 3.0, costPerBaseUnit: 0.003, totalCost: 36, supplier: "Charles", isPOSItem: false },
    { materialName: "Pickles", materialId: 36, purchasedQuantity: 10, purchasedUnit: "kg", purchasedIndividualQuantity: 10000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 10000, costPerPurchasedUnit: 5.0, costPerBaseUnit: 0.005, totalCost: 50, supplier: "Charles", isPOSItem: false },
    { materialName: "Jalapeno", materialId: 37, purchasedQuantity: 8, purchasedUnit: "kg", purchasedIndividualQuantity: 8000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 8000, costPerPurchasedUnit: 6.0, costPerBaseUnit: 0.006, totalCost: 48, supplier: "Charles", isPOSItem: false },
    { materialName: "Black Olives", materialId: 38, purchasedQuantity: 10, purchasedUnit: "kg", purchasedIndividualQuantity: 10000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 10000, costPerPurchasedUnit: 8.0, costPerBaseUnit: 0.008, totalCost: 80, supplier: "Charles", isPOSItem: false },
    { materialName: "Mango", materialId: 39, purchasedQuantity: 15, purchasedUnit: "kg", purchasedIndividualQuantity: 15000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 15000, costPerPurchasedUnit: 12.0, costPerBaseUnit: 0.012, totalCost: 180, supplier: "Charles", isPOSItem: false },
    { materialName: "Strawberry", materialId: 40, purchasedQuantity: 10, purchasedUnit: "kg", purchasedIndividualQuantity: 10000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 10000, costPerPurchasedUnit: 15.0, costPerBaseUnit: 0.015, totalCost: 150, supplier: "Charles", isPOSItem: false },
    { materialName: "Kiwi", materialId: 41, purchasedQuantity: 8, purchasedUnit: "kg", purchasedIndividualQuantity: 8000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 8000, costPerPurchasedUnit: 10.0, costPerBaseUnit: 0.01, totalCost: 80, supplier: "Charles", isPOSItem: false },
    { materialName: "Edamame", materialId: 42, purchasedQuantity: 12, purchasedUnit: "kg", purchasedIndividualQuantity: 12000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 12000, costPerPurchasedUnit: 8.0, costPerBaseUnit: 0.008, totalCost: 96, supplier: "Charles", isPOSItem: false },
    { materialName: "French Fries", materialId: 43, purchasedQuantity: 50, purchasedUnit: "kg", purchasedIndividualQuantity: 50000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 50000, costPerPurchasedUnit: 3.0, costPerBaseUnit: 0.003, totalCost: 150, supplier: "Charles", isPOSItem: false },
    { materialName: "Wedges", materialId: 44, purchasedQuantity: 40, purchasedUnit: "kg", purchasedIndividualQuantity: 40000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 40000, costPerPurchasedUnit: 3.5, costPerBaseUnit: 0.0035, totalCost: 140, supplier: "Charles", isPOSItem: false },
    { materialName: "Curly Fries", materialId: 45, purchasedQuantity: 30, purchasedUnit: "kg", purchasedIndividualQuantity: 30000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 30000, costPerPurchasedUnit: 4.0, costPerBaseUnit: 0.004, totalCost: 120, supplier: "Charles", isPOSItem: false },
    { materialName: "Mashed Potatoes", materialId: 46, purchasedQuantity: 25, purchasedUnit: "kg", purchasedIndividualQuantity: 25000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 25000, costPerPurchasedUnit: 2.8, costPerBaseUnit: 0.0028, totalCost: 70, supplier: "Charles", isPOSItem: false },
    { materialName: "Coleslaw", materialId: 47, purchasedQuantity: 15, purchasedUnit: "kg", purchasedIndividualQuantity: 15000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 15000, costPerPurchasedUnit: 4.5, costPerBaseUnit: 0.0045, totalCost: 67.5, supplier: "Charles", isPOSItem: false },
    { materialName: "Mixed Greens", materialId: 48, purchasedQuantity: 20, purchasedUnit: "kg", purchasedIndividualQuantity: 20000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 20000, costPerPurchasedUnit: 6.0, costPerBaseUnit: 0.006, totalCost: 120, supplier: "Charles", isPOSItem: false },

    // =============================================================================
    // GRAINS & CARBS
    // =============================================================================
    { materialName: "Burger Bun", materialId: 49, purchasedQuantity: 200, purchasedUnit: "piece", purchasedIndividualQuantity: 200, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "piece", purchasedConvertedQuantity: 200, costPerPurchasedUnit: 0.5, costPerBaseUnit: 0.5, totalCost: 100, supplier: "Charles", isPOSItem: false },
    { materialName: "Sandwich Bread", materialId: 50, purchasedQuantity: 100, purchasedUnit: "piece", purchasedIndividualQuantity: 100, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "piece", purchasedConvertedQuantity: 100, costPerPurchasedUnit: 0.4, costPerBaseUnit: 0.4, totalCost: 40, supplier: "Charles", isPOSItem: false },
    { materialName: "Pita Bread", materialId: 51, purchasedQuantity: 150, purchasedUnit: "piece", purchasedIndividualQuantity: 150, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "piece", purchasedConvertedQuantity: 150, costPerPurchasedUnit: 0.3, costPerBaseUnit: 0.3, totalCost: 45, supplier: "Charles", isPOSItem: false },
    { materialName: "Sajj Bread", materialId: 52, purchasedQuantity: 100, purchasedUnit: "piece", purchasedIndividualQuantity: 100, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "piece", purchasedConvertedQuantity: 100, costPerPurchasedUnit: 0.35, costPerBaseUnit: 0.35, totalCost: 35, supplier: "Charles", isPOSItem: false },
    { materialName: "Pizza Dough", materialId: 53, purchasedQuantity: 50, purchasedUnit: "piece", purchasedIndividualQuantity: 50, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "piece", purchasedConvertedQuantity: 50, costPerPurchasedUnit: 1.2, costPerBaseUnit: 1.2, totalCost: 60, supplier: "Charles", isPOSItem: false },
    { materialName: "Penne", materialId: 54, purchasedQuantity: 25, purchasedUnit: "kg", purchasedIndividualQuantity: 25000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 25000, costPerPurchasedUnit: 3.5, costPerBaseUnit: 0.0035, totalCost: 87.5, supplier: "Charles", isPOSItem: false },
    { materialName: "Tagliatelle", materialId: 55, purchasedQuantity: 20, purchasedUnit: "kg", purchasedIndividualQuantity: 20000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 20000, costPerPurchasedUnit: 4.0, costPerBaseUnit: 0.004, totalCost: 80, supplier: "Charles", isPOSItem: false },
    { materialName: "Linguine", materialId: 56, purchasedQuantity: 15, purchasedUnit: "kg", purchasedIndividualQuantity: 15000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 15000, costPerPurchasedUnit: 4.2, costPerBaseUnit: 0.0042, totalCost: 63, supplier: "Charles", isPOSItem: false },
    { materialName: "Fresh Noodles", materialId: 57, purchasedQuantity: 20, purchasedUnit: "kg", purchasedIndividualQuantity: 20000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 20000, costPerPurchasedUnit: 5.0, costPerBaseUnit: 0.005, totalCost: 100, supplier: "Charles", isPOSItem: false },
    { materialName: "White Rice", materialId: 58, purchasedQuantity: 30, purchasedUnit: "kg", purchasedIndividualQuantity: 30000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 30000, costPerPurchasedUnit: 2.8, costPerBaseUnit: 0.0028, totalCost: 84, supplier: "Charles", isPOSItem: false },
    { materialName: "Sushi Rice", materialId: 59, purchasedQuantity: 25, purchasedUnit: "kg", purchasedIndividualQuantity: 25000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 25000, costPerPurchasedUnit: 4.0, costPerBaseUnit: 0.004, totalCost: 100, supplier: "Charles", isPOSItem: false },
    { materialName: "Quinoa", materialId: 60, purchasedQuantity: 15, purchasedUnit: "kg", purchasedIndividualQuantity: 15000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 15000, costPerPurchasedUnit: 8.0, costPerBaseUnit: 0.008, totalCost: 120, supplier: "Charles", isPOSItem: false },

    // =============================================================================
    // SAUCES & CONDIMENTS
    // =============================================================================
    { materialName: "Mayo Garlic Sauce", materialId: 61, purchasedQuantity: 10, purchasedUnit: "l", purchasedIndividualQuantity: 10000, purchasedIndividualUnit: "ml", purchasedConvertedUnit: "ml", purchasedConvertedQuantity: 10000, costPerPurchasedUnit: 8.0, costPerBaseUnit: 0.008, totalCost: 80, supplier: "Charles", isPOSItem: false },
    { materialName: "BBQ Sauce", materialId: 62, purchasedQuantity: 8, purchasedUnit: "l", purchasedIndividualQuantity: 8000, purchasedIndividualUnit: "ml", purchasedConvertedUnit: "ml", purchasedConvertedQuantity: 8000, costPerPurchasedUnit: 6.0, costPerBaseUnit: 0.006, totalCost: 48, supplier: "Charles", isPOSItem: false },
    { materialName: "Marinara Sauce", materialId: 63, purchasedQuantity: 15, purchasedUnit: "l", purchasedIndividualQuantity: 15000, purchasedIndividualUnit: "ml", purchasedConvertedUnit: "ml", purchasedConvertedQuantity: 15000, costPerPurchasedUnit: 5.0, costPerBaseUnit: 0.005, totalCost: 75, supplier: "Charles", isPOSItem: false },
    { materialName: "Alfredo Sauce", materialId: 64, purchasedQuantity: 10, purchasedUnit: "l", purchasedIndividualQuantity: 10000, purchasedIndividualUnit: "ml", purchasedConvertedUnit: "ml", purchasedConvertedQuantity: 10000, costPerPurchasedUnit: 7.0, costPerBaseUnit: 0.007, totalCost: 70, supplier: "Charles", isPOSItem: false },
    { materialName: "Pesto Sauce", materialId: 65, purchasedQuantity: 6, purchasedUnit: "l", purchasedIndividualQuantity: 6000, purchasedIndividualUnit: "ml", purchasedConvertedUnit: "ml", purchasedConvertedQuantity: 6000, costPerPurchasedUnit: 12.0, costPerBaseUnit: 0.012, totalCost: 72, supplier: "Charles", isPOSItem: false },
    { materialName: "Buffalo Sauce", materialId: 66, purchasedQuantity: 5, purchasedUnit: "l", purchasedIndividualQuantity: 5000, purchasedIndividualUnit: "ml", purchasedConvertedUnit: "ml", purchasedConvertedQuantity: 5000, costPerPurchasedUnit: 8.5, costPerBaseUnit: 0.0085, totalCost: 42.5, supplier: "Charles", isPOSItem: false },
    { materialName: "Honey Mustard Sauce", materialId: 67, purchasedQuantity: 6, purchasedUnit: "l", purchasedIndividualQuantity: 6000, purchasedIndividualUnit: "ml", purchasedConvertedUnit: "ml", purchasedConvertedQuantity: 6000, costPerPurchasedUnit: 7.5, costPerBaseUnit: 0.0075, totalCost: 45, supplier: "Charles", isPOSItem: false },
    { materialName: "Caesar Sauce", materialId: 68, purchasedQuantity: 8, purchasedUnit: "l", purchasedIndividualQuantity: 8000, purchasedIndividualUnit: "ml", purchasedConvertedUnit: "ml", purchasedConvertedQuantity: 8000, costPerPurchasedUnit: 9.0, costPerBaseUnit: 0.009, totalCost: 72, supplier: "Charles", isPOSItem: false },
    { materialName: "Balsamic Sauce", materialId: 69, purchasedQuantity: 5, purchasedUnit: "l", purchasedIndividualQuantity: 5000, purchasedIndividualUnit: "ml", purchasedConvertedUnit: "ml", purchasedConvertedQuantity: 5000, costPerPurchasedUnit: 12.0, costPerBaseUnit: 0.012, totalCost: 60, supplier: "Charles", isPOSItem: false },
    { materialName: "Lemon Mayo Sauce", materialId: 70, purchasedQuantity: 8, purchasedUnit: "l", purchasedIndividualQuantity: 8000, purchasedIndividualUnit: "ml", purchasedConvertedUnit: "ml", purchasedConvertedQuantity: 8000, costPerPurchasedUnit: 8.0, costPerBaseUnit: 0.008, totalCost: 64, supplier: "Charles", isPOSItem: false },
    { materialName: "Olive Oil Sauce", materialId: 71, purchasedQuantity: 10, purchasedUnit: "l", purchasedIndividualQuantity: 10000, purchasedIndividualUnit: "ml", purchasedConvertedUnit: "ml", purchasedConvertedQuantity: 10000, costPerPurchasedUnit: 15.0, costPerBaseUnit: 0.015, totalCost: 150, supplier: "Charles", isPOSItem: false },
    { materialName: "Teriyaki Sauce", materialId: 72, purchasedQuantity: 6, purchasedUnit: "l", purchasedIndividualQuantity: 6000, purchasedIndividualUnit: "ml", purchasedConvertedUnit: "ml", purchasedConvertedQuantity: 6000, costPerPurchasedUnit: 9.0, costPerBaseUnit: 0.009, totalCost: 54, supplier: "Charles", isPOSItem: false },
    { materialName: "Soy Sauce", materialId: 73, purchasedQuantity: 5, purchasedUnit: "l", purchasedIndividualQuantity: 5000, purchasedIndividualUnit: "ml", purchasedConvertedUnit: "ml", purchasedConvertedQuantity: 5000, costPerPurchasedUnit: 8.0, costPerBaseUnit: 0.008, totalCost: 40, supplier: "Charles", isPOSItem: false },
    { materialName: "Ketchup", materialId: 74, purchasedQuantity: 12, purchasedUnit: "l", purchasedIndividualQuantity: 12000, purchasedIndividualUnit: "ml", purchasedConvertedUnit: "ml", purchasedConvertedQuantity: 12000, costPerPurchasedUnit: 4.0, costPerBaseUnit: 0.004, totalCost: 48, supplier: "Charles", isPOSItem: false },
    { materialName: "Zaatar", materialId: 75, purchasedQuantity: 8, purchasedUnit: "kg", purchasedIndividualQuantity: 8000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 8000, costPerPurchasedUnit: 12.0, costPerBaseUnit: 0.012, totalCost: 96, supplier: "Charles", isPOSItem: false },
    { materialName: "Cheese Sauce", materialId: 76, purchasedQuantity: 8, purchasedUnit: "l", purchasedIndividualQuantity: 8000, purchasedIndividualUnit: "ml", purchasedConvertedUnit: "ml", purchasedConvertedQuantity: 8000, costPerPurchasedUnit: 9.0, costPerBaseUnit: 0.009, totalCost: 72, supplier: "Charles", isPOSItem: false },
    { materialName: "Cheddar Sauce", materialId: 77, purchasedQuantity: 6, purchasedUnit: "l", purchasedIndividualQuantity: 6000, purchasedIndividualUnit: "ml", purchasedConvertedUnit: "ml", purchasedConvertedQuantity: 6000, costPerPurchasedUnit: 10.0, costPerBaseUnit: 0.01, totalCost: 60, supplier: "Charles", isPOSItem: false },
    { materialName: "Creamy Sauce", materialId: 78, purchasedQuantity: 10, purchasedUnit: "l", purchasedIndividualQuantity: 10000, purchasedIndividualUnit: "ml", purchasedConvertedUnit: "ml", purchasedConvertedQuantity: 10000, costPerPurchasedUnit: 8.5, costPerBaseUnit: 0.0085, totalCost: 85, supplier: "Charles", isPOSItem: false },
    { materialName: "Fresh Mushroom", materialId: 79, purchasedQuantity: 12, purchasedUnit: "kg", purchasedIndividualQuantity: 12000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 12000, costPerPurchasedUnit: 9.0, costPerBaseUnit: 0.009, totalCost: 108, supplier: "Charles", isPOSItem: false },

    // =============================================================================
    // SUSHI INGREDIENTS
    // =============================================================================
    { materialName: "Nori Sheets", materialId: 80, purchasedQuantity: 10, purchasedUnit: "pack", purchasedIndividualQuantity: 100, purchasedIndividualUnit: "sheet", purchasedConvertedUnit: "sheet", purchasedConvertedQuantity: 100, costPerPurchasedUnit: 12.0, costPerBaseUnit: 1.2, totalCost: 120, supplier: "Charles", isPOSItem: false },
    { materialName: "Tobiko", materialId: 81, purchasedQuantity: 3, purchasedUnit: "kg", purchasedIndividualQuantity: 3000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 3000, costPerPurchasedUnit: 45.0, costPerBaseUnit: 0.045, totalCost: 135, supplier: "Charles", isPOSItem: false },
    { materialName: "Wasabi", materialId: 82, purchasedQuantity: 2, purchasedUnit: "kg", purchasedIndividualQuantity: 2000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 2000, costPerPurchasedUnit: 80.0, costPerBaseUnit: 0.08, totalCost: 160, supplier: "Charles", isPOSItem: false },
    { materialName: "Sesame Seeds", materialId: 83, purchasedQuantity: 5, purchasedUnit: "kg", purchasedIndividualQuantity: 5000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 5000, costPerPurchasedUnit: 12.0, costPerBaseUnit: 0.012, totalCost: 60, supplier: "Charles", isPOSItem: false },
    { materialName: "Crispy Flakes", materialId: 84, purchasedQuantity: 8, purchasedUnit: "kg", purchasedIndividualQuantity: 8000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 8000, costPerPurchasedUnit: 15.0, costPerBaseUnit: 0.015, totalCost: 120, supplier: "Charles", isPOSItem: false },

    // =============================================================================
    // NUTS & EXTRAS
    // =============================================================================
    { materialName: "Walnuts", materialId: 85, purchasedQuantity: 8, purchasedUnit: "kg", purchasedIndividualQuantity: 8000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 8000, costPerPurchasedUnit: 18.0, costPerBaseUnit: 0.018, totalCost: 144, supplier: "Charles", isPOSItem: false },
    { materialName: "Cashew", materialId: 86, purchasedQuantity: 6, purchasedUnit: "kg", purchasedIndividualQuantity: 6000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 6000, costPerPurchasedUnit: 22.0, costPerBaseUnit: 0.022, totalCost: 132, supplier: "Charles", isPOSItem: false },
    { materialName: "Croutons", materialId: 87, purchasedQuantity: 10, purchasedUnit: "kg", purchasedIndividualQuantity: 10000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 10000, costPerPurchasedUnit: 8.0, costPerBaseUnit: 0.008, totalCost: 80, supplier: "Charles", isPOSItem: false },
    { materialName: "Dried Fruits", materialId: 88, purchasedQuantity: 5, purchasedUnit: "kg", purchasedIndividualQuantity: 5000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 5000, costPerPurchasedUnit: 20.0, costPerBaseUnit: 0.02, totalCost: 100, supplier: "Charles", isPOSItem: false },
    { materialName: "Cranberry", materialId: 89, purchasedQuantity: 4, purchasedUnit: "kg", purchasedIndividualQuantity: 4000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 4000, costPerPurchasedUnit: 25.0, costPerBaseUnit: 0.025, totalCost: 100, supplier: "Charles", isPOSItem: false },
    { materialName: "Dried Figs", materialId: 90, purchasedQuantity: 3, purchasedUnit: "kg", purchasedIndividualQuantity: 3000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 3000, costPerPurchasedUnit: 22.0, costPerBaseUnit: 0.022, totalCost: 66, supplier: "Charles", isPOSItem: false },

    // =============================================================================
    // BEVERAGES - BEERS & ENERGY DRINKS
    // =============================================================================
    { materialName: "Mexican Red Bull", materialId: 91, purchasedQuantity: 48, purchasedUnit: "piece", purchasedIndividualQuantity: 48, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "piece", purchasedConvertedQuantity: 48, costPerPurchasedUnit: 3.5, costPerBaseUnit: 3.5, totalCost: 168, supplier: "Charles", isPOSItem: true },
    { materialName: "Almaza", materialId: 92, purchasedQuantity: 72, purchasedUnit: "piece", purchasedIndividualQuantity: 72, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "piece", purchasedConvertedQuantity: 72, costPerPurchasedUnit: 2.5, costPerBaseUnit: 2.5, totalCost: 180, supplier: "Charles", isPOSItem: true },
    { materialName: "Almaza Light", materialId: 93, purchasedQuantity: 48, purchasedUnit: "piece", purchasedIndividualQuantity: 48, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "piece", purchasedConvertedQuantity: 48, costPerPurchasedUnit: 3.2, costPerBaseUnit: 3.2, totalCost: 153.6, supplier: "Charles", isPOSItem: true },
    { materialName: "Mexican Beer", materialId: 94, purchasedQuantity: 60, purchasedUnit: "piece", purchasedIndividualQuantity: 60, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "piece", purchasedConvertedQuantity: 60, costPerPurchasedUnit: 3.2, costPerBaseUnit: 3.2, totalCost: 192, supplier: "Charles", isPOSItem: true },
    { materialName: "Almaza Rose", materialId: 95, purchasedQuantity: 36, purchasedUnit: "piece", purchasedIndividualQuantity: 36, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "piece", purchasedConvertedQuantity: 36, costPerPurchasedUnit: 4.0, costPerBaseUnit: 4.0, totalCost: 144, supplier: "Charles", isPOSItem: true },
    { materialName: "Mexican Energy Drink", materialId: 96, purchasedQuantity: 48, purchasedUnit: "piece", purchasedIndividualQuantity: 48, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "piece", purchasedConvertedQuantity: 48, costPerPurchasedUnit: 2.8, costPerBaseUnit: 2.8, totalCost: 134.4, supplier: "Charles", isPOSItem: true },

    // =============================================================================
    // BEVERAGES - WINES
    // =============================================================================
    { materialName: "Ksara Red Wine Glass", materialId: 97, purchasedQuantity: 100, purchasedUnit: "piece", purchasedIndividualQuantity: 100, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "piece", purchasedConvertedQuantity: 100, costPerPurchasedUnit: 3.0, costPerBaseUnit: 3.0, totalCost: 300, supplier: "Charles", isPOSItem: true },
    { materialName: "Ksara Red Wine Bottle", materialId: 98, purchasedQuantity: 24, purchasedUnit: "piece", purchasedIndividualQuantity: 24, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "piece", purchasedConvertedQuantity: 24, costPerPurchasedUnit: 18.0, costPerBaseUnit: 18.0, totalCost: 432, supplier: "Charles", isPOSItem: true },
    { materialName: "Ksara White Wine Glass", materialId: 99, purchasedQuantity: 100, purchasedUnit: "piece", purchasedIndividualQuantity: 100, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "piece", purchasedConvertedQuantity: 100, costPerPurchasedUnit: 3.0, costPerBaseUnit: 3.0, totalCost: 300, supplier: "Charles", isPOSItem: true },
    { materialName: "Ksara White Wine Bottle", materialId: 100, purchasedQuantity: 24, purchasedUnit: "piece", purchasedIndividualQuantity: 24, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "piece", purchasedConvertedQuantity: 24, costPerPurchasedUnit: 18.0, costPerBaseUnit: 18.0, totalCost: 432, supplier: "Charles", isPOSItem: true },
    { materialName: "Ksara Rose Wine Glass", materialId: 101, purchasedQuantity: 100, purchasedUnit: "piece", purchasedIndividualQuantity: 100, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "piece", purchasedConvertedQuantity: 100, costPerPurchasedUnit: 3.0, costPerBaseUnit: 3.0, totalCost: 300, supplier: "Charles", isPOSItem: true },
    { materialName: "Ksara Rose Wine Bottle", materialId: 102, purchasedQuantity: 24, purchasedUnit: "piece", purchasedIndividualQuantity: 24, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "piece", purchasedConvertedQuantity: 24, costPerPurchasedUnit: 18.0, costPerBaseUnit: 18.0, totalCost: 432, supplier: "Charles", isPOSItem: true },

    // =============================================================================
    // BEVERAGES - SPIRITS (BOTTLES)
    // =============================================================================
    { materialName: "Jose Cuervo Silver Bottle", materialId: 103, purchasedQuantity: 12, purchasedUnit: "piece", purchasedIndividualQuantity: 12, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "piece", purchasedConvertedQuantity: 12, costPerPurchasedUnit: 25.0, costPerBaseUnit: 25.0, totalCost: 300, supplier: "Charles", isPOSItem: true },
    { materialName: "Jose Cuervo Gold Bottle", materialId: 104, purchasedQuantity: 8, purchasedUnit: "piece", purchasedIndividualQuantity: 8, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "piece", purchasedConvertedQuantity: 8, costPerPurchasedUnit: 38.0, costPerBaseUnit: 38.0, totalCost: 304, supplier: "Charles", isPOSItem: true },
    { materialName: "Beefeater Bottle", materialId: 105, purchasedQuantity: 6, purchasedUnit: "piece", purchasedIndividualQuantity: 6, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "piece", purchasedConvertedQuantity: 6, costPerPurchasedUnit: 45.0, costPerBaseUnit: 45.0, totalCost: 270, supplier: "Charles", isPOSItem: true },
    { materialName: "Tanqueray Bottle", materialId: 106, purchasedQuantity: 6, purchasedUnit: "piece", purchasedIndividualQuantity: 6, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "piece", purchasedConvertedQuantity: 6, costPerPurchasedUnit: 52.0, costPerBaseUnit: 52.0, totalCost: 312, supplier: "Charles", isPOSItem: true },
    { materialName: "Bombay Bottle", materialId: 107, purchasedQuantity: 8, purchasedUnit: "piece", purchasedIndividualQuantity: 8, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "piece", purchasedConvertedQuantity: 8, costPerPurchasedUnit: 32.0, costPerBaseUnit: 32.0, totalCost: 256, supplier: "Charles", isPOSItem: true },
    { materialName: "Gordons Bottle", materialId: 108, purchasedQuantity: 8, purchasedUnit: "piece", purchasedIndividualQuantity: 8, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "piece", purchasedConvertedQuantity: 8, costPerPurchasedUnit: 42.0, costPerBaseUnit: 42.0, totalCost: 336, supplier: "Charles", isPOSItem: true },
    { materialName: "J&B Bottle", materialId: 109, purchasedQuantity: 6, purchasedUnit: "piece", purchasedIndividualQuantity: 6, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "piece", purchasedConvertedQuantity: 6, costPerPurchasedUnit: 52.0, costPerBaseUnit: 52.0, totalCost: 312, supplier: "Charles", isPOSItem: true },
    { materialName: "Jack Daniels Bottle", materialId: 110, purchasedQuantity: 6, purchasedUnit: "piece", purchasedIndividualQuantity: 6, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "piece", purchasedConvertedQuantity: 6, costPerPurchasedUnit: 65.0, costPerBaseUnit: 65.0, totalCost: 390, supplier: "Charles", isPOSItem: true },
    { materialName: "Glenfiddich Bottle", materialId: 111, purchasedQuantity: 4, purchasedUnit: "piece", purchasedIndividualQuantity: 4, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "piece", purchasedConvertedQuantity: 4, costPerPurchasedUnit: 78.0, costPerBaseUnit: 78.0, totalCost: 312, supplier: "Charles", isPOSItem: true },
    { materialName: "Black Label Bottle", materialId: 112, purchasedQuantity: 6, purchasedUnit: "piece", purchasedIndividualQuantity: 6, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "piece", purchasedConvertedQuantity: 6, costPerPurchasedUnit: 58.0, costPerBaseUnit: 58.0, totalCost: 348, supplier: "Charles", isPOSItem: true },
    { materialName: "Red Label Bottle", materialId: 113, purchasedQuantity: 8, purchasedUnit: "piece", purchasedIndividualQuantity: 8, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "piece", purchasedConvertedQuantity: 8, costPerPurchasedUnit: 42.0, costPerBaseUnit: 42.0, totalCost: 336, supplier: "Charles", isPOSItem: true },
    { materialName: "Jameson Bottle", materialId: 114, purchasedQuantity: 6, purchasedUnit: "piece", purchasedIndividualQuantity: 6, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "piece", purchasedConvertedQuantity: 6, costPerPurchasedUnit: 45.0, costPerBaseUnit: 45.0, totalCost: 270, supplier: "Charles", isPOSItem: true },
    { materialName: "Chivas 12y Bottle", materialId: 115, purchasedQuantity: 4, purchasedUnit: "piece", purchasedIndividualQuantity: 4, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "piece", purchasedConvertedQuantity: 4, costPerPurchasedUnit: 65.0, costPerBaseUnit: 65.0, totalCost: 260, supplier: "Charles", isPOSItem: true },
    { materialName: "Chivas 15y Bottle", materialId: 116, purchasedQuantity: 3, purchasedUnit: "piece", purchasedIndividualQuantity: 3, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "piece", purchasedConvertedQuantity: 3, costPerPurchasedUnit: 98.0, costPerBaseUnit: 98.0, totalCost: 294, supplier: "Charles", isPOSItem: true },
    { materialName: "Jim Beam Bottle", materialId: 117, purchasedQuantity: 6, purchasedUnit: "piece", purchasedIndividualQuantity: 6, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "piece", purchasedConvertedQuantity: 6, costPerPurchasedUnit: 48.0, costPerBaseUnit: 48.0, totalCost: 288, supplier: "Charles", isPOSItem: true },
    { materialName: "Grey Goose Bottle", materialId: 118, purchasedQuantity: 4, purchasedUnit: "piece", purchasedIndividualQuantity: 4, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "piece", purchasedConvertedQuantity: 4, costPerPurchasedUnit: 78.0, costPerBaseUnit: 78.0, totalCost: 312, supplier: "Charles", isPOSItem: true },
    { materialName: "Belvedere Bottle", materialId: 119, purchasedQuantity: 3, purchasedUnit: "piece", purchasedIndividualQuantity: 3, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "piece", purchasedConvertedQuantity: 3, costPerPurchasedUnit: 92.0, costPerBaseUnit: 92.0, totalCost: 276, supplier: "Charles", isPOSItem: true },
    { materialName: "Stoli Gold Bottle", materialId: 120, purchasedQuantity: 6, purchasedUnit: "piece", purchasedIndividualQuantity: 6, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "piece", purchasedConvertedQuantity: 6, costPerPurchasedUnit: 65.0, costPerBaseUnit: 65.0, totalCost: 390, supplier: "Charles", isPOSItem: true },
    { materialName: "Stoli Red Bottle", materialId: 121, purchasedQuantity: 8, purchasedUnit: "piece", purchasedIndividualQuantity: 8, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "piece", purchasedConvertedQuantity: 8, costPerPurchasedUnit: 45.0, costPerBaseUnit: 45.0, totalCost: 360, supplier: "Charles", isPOSItem: true },
    { materialName: "Smirnoff Bottle", materialId: 122, purchasedQuantity: 10, purchasedUnit: "piece", purchasedIndividualQuantity: 10, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "piece", purchasedConvertedQuantity: 10, costPerPurchasedUnit: 38.0, costPerBaseUnit: 38.0, totalCost: 380, supplier: "Charles", isPOSItem: true },
    { materialName: "Russian Standard Bottle", materialId: 123, purchasedQuantity: 6, purchasedUnit: "piece", purchasedIndividualQuantity: 6, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "piece", purchasedConvertedQuantity: 6, costPerPurchasedUnit: 55.0, costPerBaseUnit: 55.0, totalCost: 330, supplier: "Charles", isPOSItem: true },

    // =============================================================================
    // BEVERAGES - SOFT DRINKS & JUICES
    // =============================================================================
    { materialName: "Red Bull", materialId: 124, purchasedQuantity: 72, purchasedUnit: "piece", purchasedIndividualQuantity: 72, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "piece", purchasedConvertedQuantity: 72, costPerPurchasedUnit: 3.2, costPerBaseUnit: 3.2, totalCost: 230.4, supplier: "Charles", isPOSItem: true },
    { materialName: "Water Small", materialId: 125, purchasedQuantity: 200, purchasedUnit: "piece", purchasedIndividualQuantity: 200, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "piece", purchasedConvertedQuantity: 200, costPerPurchasedUnit: 0.8, costPerBaseUnit: 0.8, totalCost: 160, supplier: "Charles", isPOSItem: true },
    { materialName: "Water Large", materialId: 126, purchasedQuantity: 100, purchasedUnit: "piece", purchasedIndividualQuantity: 100, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "piece", purchasedConvertedQuantity: 100, costPerPurchasedUnit: 1.8, costPerBaseUnit: 1.8, totalCost: 180, supplier: "Charles", isPOSItem: true },
    { materialName: "Soft Drinks", materialId: 127, purchasedQuantity: 120, purchasedUnit: "piece", purchasedIndividualQuantity: 120, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "piece", purchasedConvertedQuantity: 120, costPerPurchasedUnit: 1.8, costPerBaseUnit: 1.8, totalCost: 216, supplier: "Charles", isPOSItem: true },
    { materialName: "Sparkling Water", materialId: 128, purchasedQuantity: 60, purchasedUnit: "piece", purchasedIndividualQuantity: 60, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "piece", purchasedConvertedQuantity: 60, costPerPurchasedUnit: 2.5, costPerBaseUnit: 2.5, totalCost: 150, supplier: "Charles", isPOSItem: true },
    { materialName: "Energy Drink", materialId: 129, purchasedQuantity: 72, purchasedUnit: "piece", purchasedIndividualQuantity: 72, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "piece", purchasedConvertedQuantity: 72, costPerPurchasedUnit: 2.5, costPerBaseUnit: 2.5, totalCost: 180, supplier: "Charles", isPOSItem: true },

    // =============================================================================
    // BEVERAGES - COFFEE INGREDIENTS
    // =============================================================================
    { materialName: "Coffee Beans", materialId: 130, purchasedQuantity: 25, purchasedUnit: "kg", purchasedIndividualQuantity: 25000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 25000, costPerPurchasedUnit: 18.0, costPerBaseUnit: 0.018, totalCost: 450, supplier: "Charles", isPOSItem: false },
    { materialName: "Milk", materialId: 131, purchasedQuantity: 50, purchasedUnit: "l", purchasedIndividualQuantity: 50000, purchasedIndividualUnit: "ml", purchasedConvertedUnit: "ml", purchasedConvertedQuantity: 50000, costPerPurchasedUnit: 1.2, costPerBaseUnit: 0.0012, totalCost: 60, supplier: "Charles", isPOSItem: false },
    { materialName: "Sugar", materialId: 132, purchasedQuantity: 20, purchasedUnit: "kg", purchasedIndividualQuantity: 20000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 20000, costPerPurchasedUnit: 2.5, costPerBaseUnit: 0.0025, totalCost: 50, supplier: "Charles", isPOSItem: false },
    { materialName: "Vanilla Syrup", materialId: 133, purchasedQuantity: 10, purchasedUnit: "l", purchasedIndividualQuantity: 10000, purchasedIndividualUnit: "ml", purchasedConvertedUnit: "ml", purchasedConvertedQuantity: 10000, costPerPurchasedUnit: 8.0, costPerBaseUnit: 0.008, totalCost: 80, supplier: "Charles", isPOSItem: false },
    { materialName: "Caramel Syrup", materialId: 134, purchasedQuantity: 10, purchasedUnit: "l", purchasedIndividualQuantity: 10000, purchasedIndividualUnit: "ml", purchasedConvertedUnit: "ml", purchasedConvertedQuantity: 10000, costPerPurchasedUnit: 8.5, costPerBaseUnit: 0.0085, totalCost: 85, supplier: "Charles", isPOSItem: false },
    { materialName: "Chocolate Syrup", materialId: 135, purchasedQuantity: 8, purchasedUnit: "l", purchasedIndividualQuantity: 8000, purchasedIndividualUnit: "ml", purchasedConvertedUnit: "ml", purchasedConvertedQuantity: 8000, costPerPurchasedUnit: 9.0, costPerBaseUnit: 0.009, totalCost: 72, supplier: "Charles", isPOSItem: false },
    { materialName: "Whipped Cream", materialId: 136, purchasedQuantity: 15, purchasedUnit: "l", purchasedIndividualQuantity: 15000, purchasedIndividualUnit: "ml", purchasedConvertedUnit: "ml", purchasedConvertedQuantity: 15000, costPerPurchasedUnit: 6.0, costPerBaseUnit: 0.006, totalCost: 90, supplier: "Charles", isPOSItem: false },

    // =============================================================================
    // BEVERAGES - SMOOTHIE INGREDIENTS
    // =============================================================================
    { materialName: "Frozen Mango", materialId: 137, purchasedQuantity: 20, purchasedUnit: "kg", purchasedIndividualQuantity: 20000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 20000, costPerPurchasedUnit: 8.0, costPerBaseUnit: 0.008, totalCost: 160, supplier: "Charles", isPOSItem: false },
    { materialName: "Frozen Strawberries", materialId: 138, purchasedQuantity: 18, purchasedUnit: "kg", purchasedIndividualQuantity: 18000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 18000, costPerPurchasedUnit: 9.0, costPerBaseUnit: 0.009, totalCost: 162, supplier: "Charles", isPOSItem: false },
    { materialName: "Frozen Mixed Berries", materialId: 139, purchasedQuantity: 15, purchasedUnit: "kg", purchasedIndividualQuantity: 15000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 15000, costPerPurchasedUnit: 12.0, costPerBaseUnit: 0.012, totalCost: 180, supplier: "Charles", isPOSItem: false },
    { materialName: "Frozen Peaches", materialId: 140, purchasedQuantity: 15, purchasedUnit: "kg", purchasedIndividualQuantity: 15000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 15000, costPerPurchasedUnit: 8.5, costPerBaseUnit: 0.0085, totalCost: 127.5, supplier: "Charles", isPOSItem: false },
    { materialName: "Passion Fruit Pulp", materialId: 141, purchasedQuantity: 8, purchasedUnit: "kg", purchasedIndividualQuantity: 8000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 8000, costPerPurchasedUnit: 15.0, costPerBaseUnit: 0.015, totalCost: 120, supplier: "Charles", isPOSItem: false },
    { materialName: "Ice Cream Vanilla", materialId: 142, purchasedQuantity: 20, purchasedUnit: "l", purchasedIndividualQuantity: 20000, purchasedIndividualUnit: "ml", purchasedConvertedUnit: "ml", purchasedConvertedQuantity: 20000, costPerPurchasedUnit: 8.0, costPerBaseUnit: 0.008, totalCost: 160, supplier: "Charles", isPOSItem: false },
    { materialName: "Ice Cream Chocolate", materialId: 143, purchasedQuantity: 15, purchasedUnit: "l", purchasedIndividualQuantity: 15000, purchasedIndividualUnit: "ml", purchasedConvertedUnit: "ml", purchasedConvertedQuantity: 15000, costPerPurchasedUnit: 8.5, costPerBaseUnit: 0.0085, totalCost: 127.5, supplier: "Charles", isPOSItem: false },
    { materialName: "Banana", materialId: 144, purchasedQuantity: 50, purchasedUnit: "kg", purchasedIndividualQuantity: 50000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 50000, costPerPurchasedUnit: 2.5, costPerBaseUnit: 0.0025, totalCost: 125, supplier: "Charles", isPOSItem: false },
    { materialName: "Honey", materialId: 145, purchasedQuantity: 10, purchasedUnit: "l", purchasedIndividualQuantity: 10000, purchasedIndividualUnit: "ml", purchasedConvertedUnit: "ml", purchasedConvertedQuantity: 10000, costPerPurchasedUnit: 12.0, costPerBaseUnit: 0.012, totalCost: 120, supplier: "Charles", isPOSItem: false },

    // =============================================================================
    // BEVERAGES - COCKTAIL INGREDIENTS
    // =============================================================================
    { materialName: "Lime Juice", materialId: 146, purchasedQuantity: 15, purchasedUnit: "l", purchasedIndividualQuantity: 15000, purchasedIndividualUnit: "ml", purchasedConvertedUnit: "ml", purchasedConvertedQuantity: 15000, costPerPurchasedUnit: 12.0, costPerBaseUnit: 0.012, totalCost: 180, supplier: "Charles", isPOSItem: false },
    { materialName: "Lemon Juice", materialId: 147, purchasedQuantity: 15, purchasedUnit: "l", purchasedIndividualQuantity: 15000, purchasedIndividualUnit: "ml", purchasedConvertedUnit: "ml", purchasedConvertedQuantity: 15000, costPerPurchasedUnit: 11.0, costPerBaseUnit: 0.011, totalCost: 165, supplier: "Charles", isPOSItem: false },
    { materialName: "Orange Juice", materialId: 148, purchasedQuantity: 25, purchasedUnit: "l", purchasedIndividualQuantity: 25000, purchasedIndividualUnit: "ml", purchasedConvertedUnit: "ml", purchasedConvertedQuantity: 25000, costPerPurchasedUnit: 8.0, costPerBaseUnit: 0.008, totalCost: 200, supplier: "Charles", isPOSItem: false },
    { materialName: "Cranberry Juice", materialId: 149, purchasedQuantity: 12, purchasedUnit: "l", purchasedIndividualQuantity: 12000, purchasedIndividualUnit: "ml", purchasedConvertedUnit: "ml", purchasedConvertedQuantity: 12000, costPerPurchasedUnit: 10.0, costPerBaseUnit: 0.01, totalCost: 120, supplier: "Charles", isPOSItem: false },
    { materialName: "Pineapple Juice", materialId: 150, purchasedQuantity: 15, purchasedUnit: "l", purchasedIndividualQuantity: 15000, purchasedIndividualUnit: "ml", purchasedConvertedUnit: "ml", purchasedConvertedQuantity: 15000, costPerPurchasedUnit: 9.0, costPerBaseUnit: 0.009, totalCost: 135, supplier: "Charles", isPOSItem: false },
    { materialName: "Coconut Syrup", materialId: 151, purchasedQuantity: 8, purchasedUnit: "l", purchasedIndividualQuantity: 8000, purchasedIndividualUnit: "ml", purchasedConvertedUnit: "ml", purchasedConvertedQuantity: 8000, costPerPurchasedUnit: 12.0, costPerBaseUnit: 0.012, totalCost: 96, supplier: "Charles", isPOSItem: false },
    { materialName: "Blue Curacao", materialId: 152, purchasedQuantity: 6, purchasedUnit: "l", purchasedIndividualQuantity: 6000, purchasedIndividualUnit: "ml", purchasedConvertedUnit: "ml", purchasedConvertedQuantity: 6000, costPerPurchasedUnit: 25.0, costPerBaseUnit: 0.025, totalCost: 150, supplier: "Charles", isPOSItem: false },
    { materialName: "Triple Sec", materialId: 153, purchasedQuantity: 8, purchasedUnit: "l", purchasedIndividualQuantity: 8000, purchasedIndividualUnit: "ml", purchasedConvertedUnit: "ml", purchasedConvertedQuantity: 8000, costPerPurchasedUnit: 20.0, costPerBaseUnit: 0.02, totalCost: 160, supplier: "Charles", isPOSItem: false },
    { materialName: "Grenadine", materialId: 154, purchasedQuantity: 10, purchasedUnit: "l", purchasedIndividualQuantity: 10000, purchasedIndividualUnit: "ml", purchasedConvertedUnit: "ml", purchasedConvertedQuantity: 10000, costPerPurchasedUnit: 8.0, costPerBaseUnit: 0.008, totalCost: 80, supplier: "Charles", isPOSItem: false },
    { materialName: "Simple Syrup", materialId: 155, purchasedQuantity: 15, purchasedUnit: "l", purchasedIndividualQuantity: 15000, purchasedIndividualUnit: "ml", purchasedConvertedUnit: "ml", purchasedConvertedQuantity: 15000, costPerPurchasedUnit: 5.0, costPerBaseUnit: 0.005, totalCost: 75, supplier: "Charles", isPOSItem: false },
    { materialName: "Ginger Beer", materialId: 156, purchasedQuantity: 48, purchasedUnit: "piece", purchasedIndividualQuantity: 48, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "piece", purchasedConvertedQuantity: 48, costPerPurchasedUnit: 2.5, costPerBaseUnit: 2.5, totalCost: 120, supplier: "Charles", isPOSItem: false },
    { materialName: "Tonic Water", materialId: 157, purchasedQuantity: 60, purchasedUnit: "piece", purchasedIndividualQuantity: 60, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "piece", purchasedConvertedQuantity: 60, costPerPurchasedUnit: 2.0, costPerBaseUnit: 2.0, totalCost: 120, supplier: "Charles", isPOSItem: false },
    { materialName: "Club Soda", materialId: 158, purchasedQuantity: 60, purchasedUnit: "piece", purchasedIndividualQuantity: 60, purchasedIndividualUnit: "piece", purchasedConvertedUnit: "piece", purchasedConvertedQuantity: 60, costPerPurchasedUnit: 1.8, costPerBaseUnit: 1.8, totalCost: 108, supplier: "Charles", isPOSItem: false },
    { materialName: "Fresh Mint", materialId: 159, purchasedQuantity: 5, purchasedUnit: "kg", purchasedIndividualQuantity: 5000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 5000, costPerPurchasedUnit: 15.0, costPerBaseUnit: 0.015, totalCost: 75, supplier: "Charles", isPOSItem: false },
    { materialName: "Fresh Basil", materialId: 160, purchasedQuantity: 3, purchasedUnit: "kg", purchasedIndividualQuantity: 3000, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 3000, costPerPurchasedUnit: 18.0, costPerBaseUnit: 0.018, totalCost: 54, supplier: "Charles", isPOSItem: false },

    // =============================================================================
    // SHISHA SUPPLIES
    // =============================================================================
    { materialName: "Tobacco", materialId: 161, purchasedQuantity: 50, purchasedUnit: "g", purchasedIndividualQuantity: 50, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 50, costPerPurchasedUnit: 0.5, costPerBaseUnit: 0.5, totalCost: 25, supplier: "Charles", isPOSItem: false },
    { materialName: "Charcoal", materialId: 162, purchasedQuantity: 100, purchasedUnit: "g", purchasedIndividualQuantity: 100, purchasedIndividualUnit: "g", purchasedConvertedUnit: "g", purchasedConvertedQuantity: 100, costPerPurchasedUnit: 0.3, costPerBaseUnit: 0.3, totalCost: 30, supplier: "Charles", isPOSItem: false }
  ];

  let createdCount = 0;
  let skippedCount = 0;

  for (const entryData of stockEntries) {
    try {
      const material = materialMap[entryData.materialName];
      if (!material) {
        console.log(`⚠️  Material not found: ${entryData.materialName}`);
        skippedCount++;
        continue;
      }

      // Check if stock entry already exists
      const existingEntry = await StockEntry.findOne({
        where: {
          materialId: material.id,
          supplier: entryData.supplier
        }
      });

      if (!existingEntry) {
        const stockEntryData = {
          materialId: material.id,
          supplier: entryData.supplier,
          purchasedQuantity: entryData.purchasedQuantity,
          purchasedUnit: entryData.purchasedUnit,
          purchasedIndividualQuantity: entryData.purchasedIndividualQuantity,
          purchasedIndividualUnit: entryData.purchasedIndividualUnit,
          purchasedConvertedUnit: entryData.purchasedConvertedUnit,
          purchasedConvertedQuantity: entryData.purchasedConvertedQuantity,
          costPerPurchasedUnit: entryData.costPerPurchasedUnit,
          costPerBaseUnit: entryData.costPerBaseUnit,
          totalCost: entryData.totalCost,
          isPOSItem: entryData.isPOSItem,
          purchaseDate: new Date(),
          expiryDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000) // 30 days from now
        };

        await StockEntry.create(stockEntryData);
        console.log(`✅ Created stock entry: ${entryData.materialName} - ${entryData.purchasedQuantity} ${entryData.purchasedUnit}`);
        createdCount++;
      } else {
        console.log(`⏭️  Skipped existing stock entry: ${entryData.materialName} - ${entryData.supplier}`);
        skippedCount++;
      }
    } catch (error) {
      console.error(`❌ Error creating stock entry for ${entryData.materialName}:`, error.message);
      skippedCount++;
    }
  }

  return { created: createdCount, skipped: skippedCount };
}
